### 

POST http://localhost:3333/api/auth/generate-signup-otp/+19999999999 HTTP/1.1
Content-Type: application/json


### 

POST http://localhost:5000/api/auth/verify-signup-otp HTTP/1.1
Content-Type: application/json

{
  "name": "Erfan Aalam",
  "otp": 123456,
  "phone": "+91 8930647364",
  "role": "user"
}


### 

POST http://localhost:5000/api/auth/verify-signup-otp HTTP/1.1
Content-Type: application/json

{
  "name": "random user 2",
  "otp": 123456,
  "phone": "1234567890",
  "role": "user"
}


### 

POST http://localhost:5000/api/auth/verify-signup-otp HTTP/1.1
Content-Type: application/json

{
  "name": "Krishna",
  "otp": 123456,
  "phone": "8534946840",
  "role": "user"
}


### 

POST http://localhost:5000/api/auth/verify-signup-otp HTTP/1.1
Content-Type: application/json

{
  "name": "random user",
  "otp": 123456,
  "phone": "9999999999",
  "role": "user"
}


### 

POST http://localhost:5000/api/auth/generate-login-otp/9999999999 HTTP/1.1
Content-Type: application/json


### 

POST http://localhost:5000/api/auth/verify-login-otp HTTP/1.1
Content-Type: application/json

{
  "otp": 123456,
  "phone": "+919876543210"
}


### 

POST http://localhost:5000/api/auth/verify-login-otp HTTP/1.1
Content-Type: application/json

{
  "otp": 123456,
  "phone": "+918534946840"
}


### 

POST http://localhost:5000/api/auth/verify-login-otp HTTP/1.1
Content-Type: application/json

{
  "otp": 123456,
  "phone": "+911234567890"
}


### 

POST http://localhost:5000/api/auth/verify-login-otp HTTP/1.1
Content-Type: application/json

{
  "otp": 123456,
  "phone": "+918534946840"
}


### 

POST http://localhost:5000/api/chat/create-chat/6846756674 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ODMxOTA1NjYzNywicm9sZSI6InVzZXIiLCJpYXQiOjE3NTc4ODM5NDMsImV4cCI6MTc1Nzk3MDM0M30.dDO7Jjah20G2uJzcDZdhxI1E5kYUKETeO-0QME3Bq1s


### 

POST http://localhost:5000/api/chat/create-chat/7439393064 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjU5NTAzMjU3Miwicm9sZSI6InVzZXIiLCJpYXQiOjE3NTgwMjk1OTMsImV4cCI6MTc1ODExNTk5M30.-BhJGdfwjPjZny81g9QtAxc6vJegi0A8x7UhnGyi8N8


### 

GET http://localhost:5000/api/chat/get-chat-list/dm HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjU5NTAzMjU3Miwicm9sZSI6InVzZXIiLCJpYXQiOjE3NTgzNTkyMzYsImV4cCI6MTc1ODQ0NTYzNn0.IdAQQbv1twZrkoMHM6uE5Pnph70L9v0jytE8vvxANf8


### 

GET http://localhost:5000/api/user/get-user HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Njg0Njc1NjY3NCwicm9sZSI6InVzZXIiLCJpYXQiOjE3NTgwMTA0NDYsImV4cCI6MTc1ODA5Njg0Nn0.3ysXW1elf49Ta_gjqvEFDZsVJ_tYVgDeT95Lb1PVnec


### 

GET http://localhost:5000/api/user/get-user HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTk0MzgyNTQwMCwicm9sZSI6InVzZXIiLCJpYXQiOjE3NTgwMTAzNjgsImV4cCI6MTc1ODA5Njc2OH0.Ptw_XaTwtZoqHRRQf8rWqiSa6JhPloQ19QWIo8GWE_k


### 

GET http://localhost:5000/api/chat/get-conversation-history/322847238 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Njg0Njc1NjY3NCwicm9sZSI6InVzZXIiLCJpYXQiOjE3NTgzNzk5NDUsImV4cCI6MTc1ODQ2NjM0NX0.XP3Y2VqRWxf-jEhggZaEJEerEegz7OBYy-G36FBcS9s


### 

WEBSOCKET ws://localhost:5002/chat?id=6846756674 
